import type { Metadata } from "next";
import "./globals.css";
import "../../public/assets/css/bootstrap.min.css";
// import "../../public/assets/css/swiper.css";
import "../../public/assets/css/odometer.css";
import "../../public/assets/css/animation.css";
import "../../public/assets/css/feature.css";
import "../../public/assets/css/lightbox.css";
import "../../public/assets/css/magnify.min.css";
import "../../public/assets/css/slick-theme.css";
import "../../public/assets/css/slick.css";
import "../../public/assets/css/style.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
// import "swiper/css";
// import "swiper/css/pagination";
// import "swiper/css/autoplay";
import Script from "next/script";
import FloatingImagesAnimation from "./components/FloatingImagesAnimation";

export const metadata: Metadata = {
  title: "Corpox Business and Consulting NextJs Template",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/assets/images/favicon.png",
        type: "image/x-icon",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
          referrerPolicy="no-referrer"
        />
      </head>
      <body>
        {children}
        <FloatingImagesAnimation />
        <Script src="/assets/js/smooth-scroll.js" strategy="afterInteractive" />
        <Script src="/assets/js/bootstrap.min.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
